import Footer from "@/modules/footer";
import Header from "@/modules/header";
import { Cta, Paragraph, WidgetWhyUs } from "@/modules/widgets";

export default function X() {
    return <>
        <Header page={4} />
        <div className='background-2 m-auto max-w-7xl'>
            <div className='max-w-7xl m-auto background-2 p-4 sm:p-[4.5rem] text-white'>
                <div className='text-lg sm:text-3xl font-bold'>{"Designing Dreams, Inspiring Success"}</div>
                <div className='text-3xl sm:text-6xl font-bold mt-4 mb-12'>{"About DiscountDesigner"}</div>
                <div className='text-xl sm:text-4xl font-medium'>{"At DiscountDesigner, we're dreamers and creators. Our passion for design drives us to craft exceptional experiences that elevate brands and inspire success. With personalized attention, we transform ideas into captivating realities that resonate with your audience. Step into a world of boundless creativity – welcome to DiscountDesigner."}</div>
            </div>
        </div>
        <Paragraph img='/img/8.jpg' text="At Deis, our journey began with a simple vision – to fuel creativity and inspire through exceptional design. Founded by a team of passionate designers with diverse backgrounds and expertise, we set out to create a design agency that would go beyond the conventional and break new ground in the industry. We are driven by a shared commitment to excellence and a genuine love for the art of design. From our very first project to the countless brands we have elevated, our mission remains unchanged: to craft designs that resonate with people, spark emotions, and leave a lasting impact. With each collaboration, we seek to bring our clients' visions to life while adding a touch of our own magic to create designs that stand out and make a difference." route_text='Discover Our Journey' route='/services' title='Fueling Creativity and Inspiring Design' />
        <Paragraph img='/img/9.jpg' text="At DiscountDesigner, we understand that each brand is distinct, with its own identity and story to tell. That's why we take a personalized approach to every project, collaborating closely with our clients to deeply understand their values, goals, and target audience. Our designers invest time and effort in research and exploration, ensuring that every element we create aligns harmoniously with your brand's essence. From brainstorming sessions to concept development and the final execution, we keep you involved and informed every step of the way. This collaboration allows us to infuse your brand's personality and soul into every design, resulting in creations that are uniquely yours and make a memorable impact on your audience." route_text="Let's Unveil Your Brand" route='/contact' title='Designing for Your Unique Identity' />
        <Paragraph img='/img/10.jpg' text="The heart and soul of DiscountDesigner lie within our talented team of creative minds and visionaries. We are a diverse group of designers, strategists, and problem solvers who share a common passion for design and innovation. Together, we form a dynamic and collaborative environment that nurtures creativity and sparks inspiration. Our team is united by a commitment to excellence, attention to detail, and a relentless pursuit of perfection in every project we undertake. We take pride in staying at the forefront of design trends and technologies, ensuring that we deliver cutting-edge and forward-thinking solutions to our clients. When you work with DiscountDesigner, you can be confident that your brand is in the hands of dedicated professionals who truly care about your success." route_text='Meet Our Creative Team' route='/contact' title='A Collective of Creative Minds and Visionaries' />
        <Paragraph img='/img/11.jpg' text="At DiscountDesigner, we take our commitment to our clients seriously. Our promise to you is simple – to elevate your brand beyond expectations. Whether you're a startup looking to make a bold entrance into the market or an established business seeking to revitalize your brand image, we approach each project with the same dedication and enthusiasm. Our focus on quality, innovation, and exceptional client service ensures that the designs we create not only meet but exceed your goals. We measure our success by the success of our clients, and nothing brings us more joy than seeing your brand flourish with designs that make a lasting impact. Partner with us, and let's embark on a creative journey that will transform your brand and captivate your audience like never before." route_text='Elevate My Brand Today!' route='/services' title='Elevating Your Brand Beyond Expectations' />
        <Cta route='/contact' text="Ready to Stand Out? Let's Create Something Extraordinary!" />
        <WidgetWhyUs />
        <Footer />
    </>;
}